# Generated by Django 3.2.1 on 2021-05-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('students', models.ManyToManyField(related_name='subjects', to='school.Student')),
            ],
        ),
        migrations.CreateModel(
            name='PresenceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence_status', models.CharField(choices=[('present', 'present'), ('covid', 'covid'), ('absent', 'absent')], max_length=7)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
                ('subject_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
            ],
        ),
    ]
