# Generated by Django 3.2.1 on 2021-06-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_subject_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencestatus',
            name='presence_status',
            field=models.CharField(choices=[('present', 'present'), ('absent - covid', 'absent - covid'), ('absent - other', 'absent - other')], max_length=30),
        ),
    ]
